### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by mgifford** [bbc/gel#157]
Hopefully it's under the MIT or GPL or something open source.

That said, it isn't in the README and there is no LICENCE file.

**Comment by micmath** [comment]
Are you asking about the code used to generate the documentation (this project) or the documentation itself which can be found here: https://bbc.github.io/gel/

The _documentation itself_ "is published under the Open Government Licence," as stated at the bottom of every page.

The code _to generate_ the documentation is mostly `eleventy` and `md` which is hacked together with some scripts wot we wrote. I would be surprised  if anyone was interested in reusing the code used to generate the docs. It is not licensed but if that's what you're interested in let me know and I'll see what we can do to make it MIT or Apache (the two licenses I've seen used for code at the BBC).

**Comment by micmath** [comment]
Also, and I can't emphasize this enough -- it is literally stated on every page of the documentation, the example code we use in the documentation is for illustration purposes only: *it is not a library*. We optimised those code snippets for clarity  in order to best communicate specific concepts, it is left to the reader to integrate those concepts into their own framework. We don't claim copyright over any concepts illustrated in the demos of course. And hopefully you aren't asking about reuse of the demonstration code for any purpose other than as documentation, in which case the same Open Government Licence would apply.

**Comment by mgifford** [comment]
Right..  I was expecting it to be here https://github.com/bbc/gel

I just wasn't looking in the right place.

My main goal was to make sure I could add it here https://accessibility.civicactions.com/guide/design

Just want to point folks to some best practices out there.  BBC has initiated so many in the accessibility space.
