### ISSUE TITLE
Reference links are difficult to understand without additional context

### ISSUE THREAD

**Issue by JamieKnightBBC** [bbc/gel#20]
The referencing method on the promo page uses links with numbers (something like [3]).

The links appears in the link list on AT with just the number and it's unclear what the links does or is. See photos below showing the VO link list. It took me a while to understand what I was looking at.

Not sure what could be done to improve the situation. Perhaps a hidden label, or expanding the link to cover the previous sentence.

Something like 
````
<p><a href="#reference">This enables structural and navigational cues in screen reader software[1]</a></p>.
````

![img_4890](https://user-images.githubusercontent.com/18007258/47923341-0f2d3a00-deb1-11e8-8254-3d6579651577.jpg)

**Comment by micmath** [comment]
We essentially tried to follow the example of Wikipedia for our footnotes, so I shouldn't have been surprised to see that their webpages show the same issue.
![IMG_20200102_125932](https://user-images.githubusercontent.com/81645/71668295-3b1ba800-2d60-11ea-91fa-5d04466c5326.jpg)

It's hard for me to conceive of a possible solution, let alone find any research on what the best practice is here. I will do some investigation though.

**Comment by micmath** [comment]
Hugo Giraudel may have a better way to do it, and it's all CSSy! see https://www.sitepoint.com/accessible-footnotes-css/

![IMG_20200102_131047__02](https://user-images.githubusercontent.com/81645/71668780-27714100-2d62-11ea-9146-110cf0e847ef.jpg)

**Comment by micmath** [comment]
I note the final line of that article... :-)

> Huge thanks to **Heydon Pickering** for his valuable help regarding accessibility in this demo.

@Heydon

**Comment by micmath** [comment]
Before we settle on a solution it is worth noting that the implementation will be in MarkDown, since all our content is authored in that format, and is then transformed into HTML. Below are code examples of how we currently author footnotes in MarkDown and a couple possible alternatives.

NB given the CSS ninja moves referenced in the article cited above, I expect we can make all the possible implementation visually appear the same in the body of the article.

---

## Current Implementation

Not great, since the text of the footnote link is meaningless when it is displayed out of context, for example what will I see when I go to "[1]"?

```
This enables structural and navigational cues in screen reader software[^1].
```

**Result**:

```
This enables structural and navigational cues in screen reader software<a href="#f1">[1]</a>
```

---

## Alternative Implementation 1

Associate some part of the related body text to the footnote link. This seems like a fairly straightforward mechanism to build.

```
This enables structural and navigational cues in [screen reader software](^1).
```

**Result**:

```
This enables structural and navigational cues in <a href="#f1">screen reader software</a>.
```

---

## Alternative Implementation 2

Allow some screen-reader only text to be added onto the footnote link. This allows more flexibility so that you can finely control what the associated text is, but feels like a messy solution given the alternative content for AT users.

```
This enables structural and navigational cues in screen reader software[^1 Léonie Watson has published a great summary regarding testing with screen readers.].
```

**Result**:

```
This enables structural and navigational cues in screen reader software<a href="#f1">[1]<span role="note" class="sr-only">Léonie Watson has published a great summary regarding testing with screen readers.</span></a>.
```

**Comment by micmath** [comment]
Some prior art in the syntax here: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax

**Comment by micmath** [comment]
Okay, it was possible to extend the markdown parser we were using to render footnotes which allow for text to be included footnote link: https://github.com/micmath/markdown-it-footnote/blob/master/README.md

Using that fork it will be possible to enhance a footnote reference from this:

```
...multiple and redundant tab stops, impeding keyboard navigation[^5].
```
To this:
```
...multiple and redundant tab stops, impeding [^5 keyboard navigation].
```

In this case the text "keyboard navigation" will be included in the text of the link to the footnote, hopefully providing some needed context to the AT user.
